version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3006:3006'
    environment:
      - NODE_ENV=development